export const information = {
	name: "vũ hoàng diệu trung",
	email: "trungvuhoang2005@gmail.com",
	phoneNumber: "+84984041242",
	github: "https://github.com/nam246",
	bio: "Xin chào! Tôi là Trung, một Developer nghiệp dư, đam mê tạo ra những trải nghiệm web tuyệt vời. Với kiến thức về JavaScript, React, PHP và các công nghệ hiện đại, tôi chuyên xây dựng ứng dụng web từ ý tưởng đến sản phẩm hoàn thiện. Tôi luôn tìm kiếm cơ hội để học hỏi công nghệ mới và giải quyết những thách thức thú vị trong lập trình",
	skills: [
		{
			title: "Lập trình Frontend",
			description: [
				"Thành thạo: HTML5, CSS3, JavaScript (ES6+), TypeScript , Responsive Web Design.",
				"Frameworks/Libraries: ReactJS, NextJS, jQuery, Bootstrap 5, TailwindCSS.",
				"Công cụ thiết kế: Figma, Photoshop (Kiến thức căn bản).",
				"Kiểm soát phiên bản: Git, GitHub, GitLab.",
			],
		},
		{
			title: "Lập trình Backend & Database",
			description: [
				"PHP (Laravel, Wordpress) cơ bản, Java (cơ bản), Python (cơ bản).",
				"Kiến thức cơ bản về OOP.",
				"Database: MySQL, PostgreSQL, SQLite, MSSQL (Cơ bản), Oracle (cơ bản).",
				"SQL (DDL, DML, DCL, TCL), Lập trình thủ tục (PL/SQL, T-SQL).",
				"RESTful API, HTTP protocol, JWT.",
				"Kiến thức cơ bản về Docker, Docker Compose.",
				"Công cụ khác: Postman, Github Actions, GitLab CI.",
			],
		},
		{
			title: "Kỹ năng IT Support",
			description: [
				"Hệ điều hành: Windows, Ubuntu, Fedora.",
				"Microsoft Offices, Google Workspace",
				"Xử lý sự cố kỹ thuật.",
				"Công cụ hỗ trợ từ xa: TeamViewer, AnyDesk, Remote Desktop.",
				"Bảo mật dữ liệu, phần mềm diệt virus, tường lửa.",
			],
		},
		{
			title: "Kỹ năng mềm",
			description: [
				"Làm việc nhóm hiệu quả",
				"Khả năng học hỏi nhanh.",
				"Quản lý thời gian và báo cáo tiến độ.",
			],
		},
	],
	experiences: [
		{
			position: "Frontend developer",
			companyName: "G&G Fashion Co., Ltd",
			companyWebsite: "",
			startDate: "8/2025",
			endDate: "now",
			accomplishments: [
				"Phát triển giao diện web sử dụng Vue, Ant design.",
				"Hợp tác với team Backend để phát triển UI/UX cho phần mềm ERP Jeegc.",
				"Bảo trì và sửa lỗi website.",
				"Viết báo cáo tiến độ công việc hàng tuần.",
				"Làm việc theo yêu cầu của cấp trên.",
			],
		},
		{
			position: "Frontend developer",
			companyName: "Joyful Co., Ltd",
			companyWebsite: "",
			startDate: "6/2024",
			endDate: "8/2025",
			accomplishments: [
				"Phát triển giao diện web sử dụng PHP, HTML, CSS, SASS, Bootstrap, JQuery (AJAX), MySQL.",
				"Hợp tác với team UI/UX để chuyển đổi thành giao diện người dùng responsive",
				"Tối ưu hóa website cho các thiết bị di động sử dụng Media query và Bootstrap",
				"Hỗ trợ khách hàng về website hosting và domain pointing.",
				"Bảo trì và sửa lỗi website.",
				"Viết báo cáo tiến độ công việc hàng tuần.",
				"Tìm hiểu về công nghệ khác sau giờ làm việc để phục vụ việc mở rộng lĩnh vực phòng kỹ thuật theo yêu cầu của trưởng phòng",
				"Làm việc theo yêu cầu của cấp trên.",
			],
		},
		{
			position: "Frontend developer",
			companyName: "Sikido Media & Advertising Inc.",
			companyWebsite: "",
			startDate: "11/2022",
			endDate: "5/2024",
			accomplishments: [
				"Phát triển giao diện web sử dụng PHP, HTML, CSS, SASS, Bootstrap, JQuery (AJAX), MySQL.",
				"Hợp tác với team UI/UX để chuyển đổi thành giao diện người dùng responsive",
				"Tối ưu hóa website cho các thiết bị di động sử dụng Media query và Bootstrap",
				"Hỗ trợ khách hàng về website hosting và domain pointing.",
				"Bảo trì và sửa lỗi website.",
				"Viết báo cáo tiến độ công việc hàng tuần.",
				"Tìm hiểu về công nghệ khác sau giờ làm việc để phục vụ việc mở rộng lĩnh vực phòng kỹ thuật theo yêu cầu của trưởng phòng",
				"Làm việc theo yêu cầu của cấp trên.",
			],
		},
		{
			position: "Computer Technican",
			companyName: "Viễn Đông computer Ltd.",
			companyWebsite: "",
			startDate: "5/2022",
			endDate: "11/2022",
			accomplishments: [
				"Lắp ráp máy tính theo yêu cầu khách hàng.",
				"Cài đặt Windows và phần mềm theo nhu cầu.",
				"Kiểm tra và xử lý lỗi phần cứng, phần mềm.",
				"Hỗ trợ khách hàng tại văn phòng giải quyết các vấn đề máy tính.",
				"Làm việc theo yêu cầu của cấp trên.",
			],
		},
	],
	education: [
		{
			university: "Đại học Công Nghệ Thông Tin - UIT",
			major: "Công nghệ thông tin",
			degrees: "Đại học (liên thông)",
			startDate: "2024",
			endDate: "nay",
			achievements: [""],
		},
		{
			university: "Đại học Công nghiệp thành phố Hồ Chí Minh - IUH",
			major: "Công nghệ thông tin",
			degrees: "Cao Đẳng",
			startDate: "2020",
			endDate: "2022",
			achievements: [""],
		},
	],
	languages: [
		{
			name: "Tiếng Anh TOEIC 680 (Nghe, Đọc), Giao tiếp căn bản.",
			proficiency: "",
		},
		{
			name: "Tiếng Nhật JLPT N5.",
			proficiency: "",
		},
	],
};

export const projects = [
	{
		name: "bloodflame.vn",
		url: "",
		image: "/gallery/Screenshot1.png",
		techstack: ["PHP", "Bootstrap 5", "JQuery", "AJAX", "MySQL"],
	},
	{
		name: "poohhousebridal.com",
		url: "",
		image: "/gallery/Screenshot2.png",
		techstack: ["PHP", "Bootstrap 5", "JQuery", "AJAX", "MySQL"],
	},
	{
		name: "lepetitmusee.edu.vn",
		description: "",
		url: "https://lepetitmusee.edu.vn/",
		image: "/gallery/Screenshot3.png",
		techstack: ["PHP", "Bootstrap 5", "ES6", "JQuery", "AJAX", "MySQL"],
	},
	{
		name: "acecafe.vn",
		description: "",
		url: "https://acecafe.vn/",
		image: "/gallery/Screenshot4.png",
		techstack: [
			"PHP",
			"Bootstrap 5",
			"ES6",
			"JQuery",
			"AJAX",
			"particle.js",
			"MySQL",
		],
	},
	{
		name: "cdhome.vn",
		description: "",
		url: "http://demolp.free.nf/",
		image: "/gallery/cdhome.png",
		techstack: ["PHP", "ES6", "Bootstrap 5", "JQuery", "MySQL"],
	},
	{
		name: "joyfuldecor.com.vn",
		description: "",
		url: "http://joyful.free.nf/",
		image: "/gallery/Screenshot 2025-06-21 135850.png",
		techstack: ["PHP", "ES6", "Bootstrap 5", "JQuery", "MySQL"],
	},
	{
		name: "E-centre computer shop",
		description: "",
		url: "https://computer-demo-13.vercel.app/",
		image: "/gallery/computer-demo-12.png",
		techstack: [
			"NextJS",
			"ES6",
			"TypeScript",
			"TailwindCSS",
			"Payload CMS",
			"PostgresSQL",
		],
	},
	{
		name: "Thời khóa biểu của tôi",
		description: "Ứng dụng thời khóa biểu Local dùng để track thông tin học",
		url: "https://thoi-khoa-bieu.onrender.com/",
		image: "/gallery/demo-tkb-thumbnail.png",
		techstack: ["NextJS 15", "Shadcn UI", "TailwindCSS", "SQLite", "Prisma ORM"],
	},
];
